name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  Build_Test_Analyse_Merge:
    name: build_test_analyse
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.15.1'
      - run: npm install -g npm@8.1.3
      - run: npm i -g nx
      - run: npm install
      - run: npx nx affected:build --base=origin/main~1 --head=origin/main
      - run: npx nx run-many --target=test --all
