name: Targeted Deployment

on:
  push:
    branches:
      - main
    tags:
      - product/*/[1-9]+.[0-9]+.[0-9]+ #product/u-b/x.x.x
      - search/*/[1-9]+.[0-9]+.[0-9]+ #search/u-b/x.x.x

env:
  app: 'product'
  stage: 'd-b'
  environment: 'dev'
  TEST_ENV: ${{ secrets.TEST_ENV }}

jobs:
  build-deploy-product:
    name: build_deploy_product
    runs-on: ubuntu-latest
    if: startsWith (github.ref, 'refs/tags/product')
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.15.1'
      - run: npm install -g npm@8.1.3
      - run: npm i -g nx nps
      - run: npm install
      - run: npx nx run-many --target=test --all

      - name: split tag to get app, stage and environment # product/u-g/1.0.0
        uses: rishabhgupta/split-by@v1
        id: split
        with:
          string: ${{github.ref_name}}
          split-by: '/'

      - name: set app name # product
        run: |
          echo "app=${{ steps.split.outputs._0}}" >> $GITHUB_ENV
      - run: echo "app = $app"
      - name: set stage name # u-g
        run: |
          echo "stage=${{ steps.split.outputs._1}}" >> $GITHUB_ENV
      - run: echo "stage = $stage"
      - name: set environment name for DEV #dev
        if: startsWith (env.stage, 'd')
        run: |
          echo "environment=dev" >> $GITHUB_ENV
      - name: set environment name for UAT #uat
        if: startsWith (env.stage, 'u')
        run: |
          echo "environment=uat" >> $GITHUB_ENV
      - name: set environment name for PROD #prod
        if: startsWith (env.stage, 'p')
        run: |
          echo "environment=prod" >> $GITHUB_ENV
      - run: echo "environment = $environment"
      - run: nps ${app}.build.lambda.${environment}
      - run: nps ${app}.deploy.lambda.${stage}
      - run: nps ${app}.deploy.worker.${stage}

  Env_variables_test:
    name: Env_variables_test
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    env:
      Greeting: Hello
    steps:
      - name: "Say Hello Mona it's Monday"
        run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
        env:
          First_Name: Mona
